.\" generated with Ronn-NG/v0.8.0
.\" http://github.com/apjanke/ronn-ng/tree/0.8.0
.TH "SANDBOX\-APP\-LAUNCHER" "8" "April 2020" "sandbox-app-launcher" "sandbox-app-launcher Manual"
.SH "NAME"
\fBsandbox\-app\-launcher\fR \- start application in sandbox
.P
.SH "SYNOPSIS"
\fBsandbox\-app\-launcher\fR application\-name
.SH "DESCRIPTION"
TODO
.SH "EXAMPLE"
TODO
.SH "AUTHOR"
This man page has been written by Patrick Schleizer (adrelanos@riseup\.net)\.
